# Generated by Django 5.0.6 on 2024-05-23 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spots', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spot',
            name='address',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
