# Generated by Django 5.0.6 on 2024-06-10 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spots', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='spot',
            name='photo_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
