# Generated by Django 5.0.6 on 2024-06-03 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spots', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='spot',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='spot',
            name='opening_hours',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
