# Generated by Django 5.0.4 on 2024-05-20 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spots', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='spot',
            name='city',
        ),
        migrations.RemoveField(
            model_name='spot',
            name='description',
        ),
        migrations.AddField(
            model_name='spot',
            name='address',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='spot',
            name='phone',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='spot',
            name='rating',
            field=models.FloatField(max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='spot',
            name='url',
            field=models.URLField(max_length=255, null=True),
        ),
    ]
