# Generated by Django 5.0.4 on 2024-05-06 12:48

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spots', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='spots_list',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='spots_list',
            name='deleted_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='spots_list',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='spots_list',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
