# Generated by Django 5.0.4 on 2024-05-06 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spots', '0002_spots_list_created_at_spots_list_deleted_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='spots_list',
            old_name='description',
            new_name='note',
        ),
    ]
