# Generated by Django 5.0.4 on 2024-05-22 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spots', '0002_rename_city_spot_place_id_alter_spot_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='spot',
            name='city',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
