# Generated by Django 5.0.4 on 2024-05-07 20:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spots', '0003_rename_description_spots_list_note'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='spots_list',
            name='date',
        ),
    ]
