# Generated by Django 5.0.4 on 2024-05-09 06:45

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0004_remove_schedules_spot'),
        ('spots', '0004_remove_spots_list_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='spots_list',
            name='schedule',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='schedules.schedules'),
        ),
        migrations.AlterField(
            model_name='spots_list',
            name='end_time',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='spots_list',
            name='start_time',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
    ]
