# Generated by Django 5.0.4 on 2024-05-09 10:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0005_schedules_members'),
        ('spots', '0005_spots_list_schedule_alter_spots_list_end_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spots_list',
            name='schedule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedules.schedules'),
        ),
    ]
