# Generated by Django 5.0.4 on 2024-05-08 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spots', '0005_remove_spots_list_deleted_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='spots_list',
            name='deleted_at',
            field=models.DateTimeField(null=True),
        ),
    ]
