# Generated by Django 5.0.4 on 2024-05-09 08:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spots', '0006_spots_list_deleted_at'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='spots_list',
            new_name='SpotsList',
        ),
    ]
