# Generated by Django 5.0.4 on 2024-05-10 02:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spots', '0006_alter_spots_list_schedule'),
        ('spots', '0007_rename_spots_list_spotslist'),
    ]

    operations = [
    ]
