# Generated by Django 5.0.4 on 2024-05-26 07:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0003_comment_spot_comment_user'),
        ('spots', '0002_alter_spot_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='spot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='spots.spot'),
        ),
    ]
