# Generated by Django 5.0.6 on 2024-06-10 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0003_article'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Article',
        ),
    ]
