# Generated by Django 5.0.6 on 2024-06-10 22:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0003_blog_user_alter_blogcomment_user'),
        ('blogs', '0004_delete_article'),
    ]

    operations = [
    ]
