# Generated by Django 5.0.6 on 2024-06-13 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0007_alter_blog_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogcomment',
            name='rating',
        ),
    ]
