# Generated by Django 5.0.6 on 2024-05-26 08:19

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Photo',
        ),
        migrations.RemoveField(
            model_name='trip',
            name='trips_image',
        ),
        migrations.AddField(
            model_name='trip',
            name='image',
            field=models.ImageField(default=None, upload_to='trips_coverPhoto/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trip',
            name='upload_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
