# Generated by Django 5.0.4 on 2024-05-11 23:13

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
