# Generated by Django 5.0.4 on 2024-05-11 23:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0002_trip_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trip',
            name='date',
        ),
    ]
