# Generated by Django 5.0.4 on 2024-05-15 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0002_trip_member_trip_number_trip_owner_tripmember'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trip',
            name='member',
        ),
    ]
