# Generated by Django 5.0.4 on 2024-05-15 16:18

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0002_trip_member'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='member',
            field=models.ManyToManyField(related_name='trips', to=settings.AUTH_USER_MODEL),
        ),
    ]
