# Generated by Django 5.0.4 on 2024-05-17 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0003_remove_trip_member'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tripmember',
            old_name='editable',
            new_name='is_editable',
        ),
    ]
