# Generated by Django 5.0.4 on 2024-05-13 08:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0004_trip_members'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trip',
            old_name='members',
            new_name='member',
        ),
    ]
