# Generated by Django 5.0.4 on 2024-05-16 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0004_photo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Photo',
        ),
        migrations.AddField(
            model_name='trip',
            name='trips_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
