# Generated by Django 5.0.4 on 2024-05-16 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0006_rename_trips_image_trip_trip_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trip',
            name='trip_image',
        ),
        migrations.AddField(
            model_name='trip',
            name='cover_photo',
            field=models.ImageField(blank=True, default='fallback.png', upload_to=''),
        ),
    ]
