# Generated by Django 5.0.6 on 2024-06-05 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='level',
            field=models.CharField(default='基本會員', max_length=10),
        ),
    ]
