# Generated by Django 5.0.6 on 2024-05-25 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='level',
            field=models.CharField(default=None, max_length=10),
            preserve_default=False,
        ),
    ]
