# Generated by Django 5.0.6 on 2024-06-04 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='image',
            field=models.ImageField(default=None, null=True, upload_to='member_profile/'),
        ),
    ]
