# Generated by Django 5.0.4 on 2024-05-23 04:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='memberspot',
            name='deleted_at',
        ),
    ]
