# Generated by Django 5.0.6 on 2024-06-08 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_alter_member_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='image',
            field=models.ImageField(default=None, null=True, upload_to='member_profile'),
        ),
    ]
