# Generated by Django 5.0.6 on 2024-05-27 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_remove_memberspot_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='level',
            field=models.CharField(default='basic', max_length=10),
        ),
    ]
