# Generated by Django 5.0.4 on 2024-05-08 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedules',
            name='end_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='schedules',
            name='start_date',
            field=models.DateTimeField(),
        ),
    ]
