# Generated by Django 5.0.6 on 2024-06-14 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='schedule',
            options={'ordering': ['order', 'date', 'start_time']},
        ),
        migrations.AddField(
            model_name='schedule',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
