# Generated by Django 5.0.4 on 2024-05-09 05:11

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0002_alter_schedules_end_date_alter_schedules_start_date'),
        ('spots', '0004_remove_spots_list_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedules',
            name='spot',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='spots.spots_list'),
        ),
        migrations.AlterField(
            model_name='schedules',
            name='end_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='schedules',
            name='start_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
